### ISSUE TITLE
"Cannot read property 'length' of undefined" error

### ISSUE THREAD

**Issue by richard-anthony-boen** [Vonage/Grafana_Status_panel#112]
I get this error when trying this query with MySQL datasource in Status Panel plugin (I'm already using newest version 1.0.8)

SELECT
  count(*) as P
FROM processed_agw_alert_queue
WHERE $__timeFilter(receive_datetime) and service='OpenCart' and severity!='0'
Format as Table

(This query will do fine and show the result as expected in singlestat panel plugin.)

Is there something missing in my query?

Btw, here is the complete error message:

TypeError: Cannot read property 'length' of undefined
    at e.isMsResolutionNeeded (http://172.16.11.46:3000/public/build/app.3095c117813e1134f897.js:1:17572)
    at new e (http://172.16.11.46:3000/public/build/app.3095c117813e1134f897.js:1:14477)
    at StatusPluginCtrl.seriesHandler (http://172.16.11.46:3000/public/plugins/vonage-status-panel/status_ctrl.js:743:20)
    at Array.map (<anonymous>)
    at StatusPluginCtrl.onDataReceived (http://172.16.11.46:3000/public/plugins/vonage-status-panel/status_ctrl.js:669:30)
    at o.emit (http://172.16.11.46:3000/public/build/vendor.7bf3a4849cf75d02739a.js:44:25754)
    at e.emit (http://172.16.11.46:3000/public/build/app.3095c117813e1134f897.js:1:13178)
    at StatusPluginCtrl.e.handleQueryResult (http://172.16.11.46:3000/public/build/0.a84ed159b378acd7d9f2.js:7:18161)
    at u (http://172.16.11.46:3000/public/build/vendor.7bf3a4849cf75d02739a.js:87:69119)
    at http://172.16.11.46:3000/public/build/vendor.7bf3a4849cf75d02739a.js:87:69565

Any help is appreciated, thanks

**Comment by Orjanp** [comment]
A bit late, but it could be because they don't support MySQL databases. I get the same error when I try to access a Postgresql database.

**Comment by dpurge** [comment]
This needs better documentation. I spent some time trying to set up a dashboard for label data (names, version nr, status etc) coming from MSSQL query. I could not make it to work the way I want and I do not know - is it that my datasource is not supported or I just have not configured this correctly.

**Comment by hackvanru** [comment]
Up!  I have same issue with Grafana v7.0.6 I need this plugin for work witch Postgresql database. Anybody may fix it bug?
